import { config } from "./config";

// const endpoint = config?.result?.endpoint;
// const settings = config?.result?.settings;
export const API = {
  accessToken: config?.result?.endpoint?.accessToken,
  balance: config?.result?.endpoint?.balance,
  changePassword: config?.result?.endpoint?.changePassword,
  group: config?.result?.endpoint?.group,
  ladder: config?.result?.endpoint?.ladder,
  login: config?.result?.endpoint?.login,
  notification: config?.result?.endpoint?.notification,
  odds: config?.result?.endpoint?.odds,
  order: config?.result?.endpoint?.order,
  buttonValue: config?.result?.endpoint?.buttonValue,
  register: config?.result?.endpoint?.register,
  deposit: config?.result?.endpoint?.depositIframe,
  withdraw: config?.result?.endpoint?.withdrawIframe,
  ourCasino: config?.result?.endpoint?.auraCasino,
  diamondCasino: config?.result?.endpoint?.diamondCasino,
  auraCasino: config?.result?.endpoint?.auraCasino,
  myMarket: config?.result?.endpoint?.myMarket,
  competition: config?.result?.endpoint?.competition,
  searchEvent: config?.result?.endpoint?.searchEvent,
  currentBets: config?.result?.endpoint?.currentBets,
  cache: config?.result?.endpoint?.cache,
  interval: config?.result?.settings?.interval,
  exposure: config?.result?.endpoint?.exposure,
  accountStatement: config?.result?.endpoint?.accountStatement,
  settledBets: config?.result?.endpoint?.settledBets,
  siteUrl: config?.result?.settings?.siteUrl,
  whatsApp: config?.result?.endpoint?.whatsapp,
  otp: config?.result?.endpoint?.otp,
  liveCasinoWolf: config?.result?.endpoint?.liveCasinoWolf,
  slotWolf: config?.result?.endpoint?.slotsWolf,
  liveCasinoIFrame: config?.result?.endpoint?.liveCasinoIframe,
  auraWolf: config?.result?.endpoint?.auraWolf,
  assets: config?.result?.endpoint?.assets,
  bonusClaim: config?.result?.endpoint?.bonusClaim,
  referralCode: config?.result?.endpoint?.referralCode,
  banner: config?.result?.endpoint?.banner,
  bankAccount: config?.result?.endpoint?.bankAccount,
  uploadScreenshot: config?.result?.endpoint?.uploadScreenshot,
  latestEvents: config?.result?.endpoint?.latestEvents,
  downLine: config?.result?.endpoint?.downline,
  downLineEditForm: config?.result?.endpoint?.downLineEditForm,
  downLineEdit: config?.result?.endpoint?.downLineEdit,
  createDownLine: config?.result?.endpoint?.createDownLine,
  checkUsername: config?.result?.endpoint?.checkUsername,
  searchUser: config?.result?.endpoint?.searchUser,
  UserHistory: config?.result?.endpoint?.userHistory,
  partyWinLoss: config?.result?.endpoint?.partyWinLoss,
  userAuthentication: config?.result?.endpoint?.userAuthentication,
  marketAnalysis: config?.result?.endpoint?.marketAnalysis,
  adminExposure: config?.result?.endpoint?.adminExposure,
  viewBranches: config?.result?.endpoint?.viewBranches,
  addBranch: config?.result?.endpoint?.addBranch,
  socialLinks: config?.result?.endpoint?.socialLink,
  viewClients: config?.result?.endpoint?.viewClients,
  registerPanel:config?.result?.endpoint?.registerPanel,
  payments:config?.result?.endpoint?.payments,
  depositClient:config?.result?.endpoint?.depositClient,
  utr:config?.result?.endpoint?.utr
  
};

export const Settings = {
  bonus: config?.result?.settings?.bonus,
  deposit: config?.result?.settings?.deposit,
  withdraw: config?.result?.settings?.withdraw,
  register: config?.result?.settings?.registration,
  demoLogin: config?.result?.settings?.demoLogin,
  disabledDevtool: config?.result?.settings?.disabledDevtool,
  otp: config?.result?.settings?.otp,
  casinoCurrency: config?.result?.settings?.casinoCurrency,
  siteUrl: config?.result?.settings?.siteUrl,
  siteTitle: config?.result?.settings?.siteTitle,
  interval: config?.result?.settings?.interval,
  forceLogin: config?.result?.settings?.forceLogin,
  casinoType: config?.result?.settings?.casino,
};
